services:
  - type: web
    name: job-portal
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate  # ✅ THIS LINE
    startCommand: gunicorn job_portal.wsgi
